### ISSUE TITLE
Client side API call

### ISSUE THREAD

**Issue by AtulSingh-Emyre** [oss2019/CodeForces-Leaderboard#3]
On the client side, I will be sending the data as an array of the following datatype:
`{
handle: string,
email: string,
avatar: string,
firstName: string,
lastName: string,
rank: string,
rating: integer
}`

sorted by rating.
Fetch the data by making a GET server request at the route: 'localhost:5000/api/leaderboard/rankings' and display it as a leaderboard in the client side. The leaderboard may be made using an existing npm package.

**Comment by Samyc2002** [comment]
PR Made
